[package]
name = "obsidian-rs"
version = "0.1.0"
edition = "2021"
description = "A Rust library for interacting with Obsidian vaults"
repository = "https://github.com/adamisrael/obsidian-rs"
license = "MIT"
authors = ["Adam Israel <adam@adamisrael.com>"]
readme = "README.md"

[dependencies]
